language: java
jdk: oraclejdk8
env:
  # this environment variable is needed to tell geckodriver to run the browser
  # in headless mode, i.e., without an actual computer screen, which is suitable
  # for continuous integration
  - MOZ_HEADLESS=1
addons:
  firefox: "63.0.3"
  apt:
    packages:
    - dbus-x11
before_install:
  # manually install geckodriver, by downloading a specific version, which
  # we know for sure is compatible with our test
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
# added the instructions below to get rid of warning related to d-bus:
# Warning said: Client failed to connect to the D-BUS daemon:
# Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
# https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-directly
# note that dbus-x11 was also installed above for the same reason
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - geckodriver --version
  - mvn clean test